### ISSUE TITLE
positive lookahead in 'end' won't match in the beginning of the line

### ISSUE THREAD

**Issue by Ingramz** [atom/first-mate#56]
Grammar
```cson
'scopeName': 'text.broken'
'name': 'Broken grammar'
'patterns': [
  {
    'begin': 'start'
    'end': '(?=end)'
    'name': 'blue.broken'
  }
  {
    'match': '.'
    'name': 'yellow.broken'
  }
]
```

Optional highlighting for Atom:
```less
atom-text-editor::shadow {
  .blue.broken {
    color: blue;
    .yellow.broken {
      color: green;
    }
  }

  .yellow.broken {
    color: yellow;
  }
}
```

Test data
Works as expected:
```
start garbage end garbage
garbage
```

Also works as expeced
```
start garbage
wend garbage
garbage
```

Doesn't work
```
start garbage
end garbage
garbage
```

What happens is that in all 3 one should be able to see only blue and yellow separately, but it seems that lookahead doesn't want to match properly on the first character position, resulting in not leaving the blue scope, but still starting with yellow scope, which in combination gives green highlighting.

![blueyellowgreen](https://cloud.githubusercontent.com/assets/1017132/9574835/3d3c9e10-4fd3-11e5-95a8-ef79b7fb47fe.png)
